language: node_js
branches:
  only:
  - source
script: "./node_modules/.bin/gulp dist"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
notifications:
  email: false
  slack:
    rooms:
    - secure: qSB9t15fls1LkKNICZ8e0OWziJRp5P7J1ENQn2XYKfx3rbAjPCuxduPZ3tg7p2lQrHf49gofsGkcoOC+/E5cqoDbFaUJqSV/kcfne7cZjMFUBS51TD84XPT/KCfGLgXtdBJXc1aLCv2m6Nd/l6jvsuonPxOhPyU0fZwrXW2WJAKV1oXwXOFgxkSAVlZ1oKwrcVgSCpmF1WYqfGKH9G3uJTcoPT+A/w9zS9ru7Tey376cx0s6uHS7552vshc7gmnH6fQ2ICPYuTCMwjOB6a7AibYK0DHFmvZ4zHEFR02wEUi+jpd9GoTMl9bySIPP6483MuSebEErtiytIVfqQGxONWYVIEt2CqoHk7700Y3TG1FvanHofPUg1fLTPGsxEhhEKEtWfRApABQieMWkgJkFtOaLql4xKgjbGOO0Lr4ow6lDuQaLgn2HlJsVPKMfkKUB0A2rg48QqjWDL8sR4+25bc8xtJV4ae88fMikeG/SPmO07/VOWTuC0U0Qmfm+Gj2wo4zb3D0CA0fi5w3BvTMrkmL+SPXG2bnPAC6mtxzGlu2c0CIxABjHHMpq4GY3c5QL/we38GWLSVrGiqOEvuDwR3nQbuscn24PVBrh8Qvy+pu9sud2AjBCGbclLeddhXahKSGgUFHy4HCp0hT/KOujzbyOEbVljsXD2S/grKldLoM=
env:
  matrix:
    secure: RxX/1AgPK5NnFsZNTtXDgU95JJMVEcSmHp1v7V2dfVfB0RPBvyeYR4cYJWdcyzLZP4JSQENkWYKn+DQ/xMxry/I7HXglYeS6dbO1Zm/gKJHjU3q3hJDndMjj7c7dVz9tzWJ/bh4qCgFihv5sjdjOao14JuRUFKTbii+HQ4odsayAxsr6v9X7Z2qu/m6KWBATDL8FC6+ZKSg9DQVwXjNBnMhGx70GiaLsUyf8k9My1bp8MySoZ4S6vNmBIB+HNa5DCMsE9lzqV+BjWMYVr075LesOuTTXxLnc9kYKCf5J8WXLqWxrcOZcnOGVnPnzfCjm1ZHxgWmKy487TiMyGe4i6XaHFI2Tu2fzd88qW1aMBD+ob5sCACKSD176vss+x/65jA6iQDtXz4Obw8haMWfoAFULZ0r8JCy3P1Nt+8zYO0Xj87CU9QWWhv2aXapy1c23NoGO+AWg6Xwmgw5PkbQofydc2qgYIgBDZifdMWmGdw1ia2zBpO7+TawceIy3izgKtZf6FBfxIpT4BsFT308SXfHAH1fHnImdnp8dKsd8qV7KQIyAuQ9TuFD/OeCTL3R65KpGcd8ItmLDZ+R/iYJiTuPi0BgzEmh9hMphdWwI9vh9OJ9bCTYBG7OenBobat1wg7hjYZLOY5bdhSSbuWumORokh7GbEarL+4eLPDgE1G4=
