language: node_js
branches:
  only:
  - develop
script: "./node_modules/.bin/gulp dist"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: dist
  target_branch: master
  committer_from_gh: true
  on:
    branch: develop
notifications:
  email: false
  slack:
    rooms:
    - secure: qSB9t15fls1LkKNICZ8e0OWziJRp5P7J1ENQn2XYKfx3rbAjPCuxduPZ3tg7p2lQrHf49gofsGkcoOC+/E5cqoDbFaUJqSV/kcfne7cZjMFUBS51TD84XPT/KCfGLgXtdBJXc1aLCv2m6Nd/l6jvsuonPxOhPyU0fZwrXW2WJAKV1oXwXOFgxkSAVlZ1oKwrcVgSCpmF1WYqfGKH9G3uJTcoPT+A/w9zS9ru7Tey376cx0s6uHS7552vshc7gmnH6fQ2ICPYuTCMwjOB6a7AibYK0DHFmvZ4zHEFR02wEUi+jpd9GoTMl9bySIPP6483MuSebEErtiytIVfqQGxONWYVIEt2CqoHk7700Y3TG1FvanHofPUg1fLTPGsxEhhEKEtWfRApABQieMWkgJkFtOaLql4xKgjbGOO0Lr4ow6lDuQaLgn2HlJsVPKMfkKUB0A2rg48QqjWDL8sR4+25bc8xtJV4ae88fMikeG/SPmO07/VOWTuC0U0Qmfm+Gj2wo4zb3D0CA0fi5w3BvTMrkmL+SPXG2bnPAC6mtxzGlu2c0CIxABjHHMpq4GY3c5QL/we38GWLSVrGiqOEvuDwR3nQbuscn24PVBrh8Qvy+pu9sud2AjBCGbclLeddhXahKSGgUFHy4HCp0hT/KOujzbyOEbVljsXD2S/grKldLoM=
env:
  matrix:
  - secure: EXQaSanYZYx1+a+qHFM+PjlNg8g1KSx2DdPY8d6H1JZzdbN2D878mKEjWR0/m2g3hyifDyB1MfST7hHtfnHQ9vhJVCFftVIHcoIe1rekgnCLZnV7Wp54K93zz1jh7AS7RdNKDz2yZ7k1xm7Dq3a5uCHrUx7cxgNOXb+FPmoxTMfUtyxEFOOl1HVEYj8n9Wqf0BlLLyjVyOFlKZTUKxED4frkNg46wG8/hbJ9+qbeYczCUrwprfPbOkzBAPPu0WgAX6dwGDml3P41VZu/b9nBZJvuLK1871zKQSClYMWJbMF1aKbMHg3/Lz+F1kMBLEk7ZqznHZq8hIm22woCBqY0Gvv2QDNqSFQ9C56rplwea0zyytC2nrNcRivwqb2MDiOpZkchur23Q4yIeoXboUwG8kqfNwaZ/3TbdZkGw7z18ZyeOq2FlauUQefK/EtKViQG55zKi/Kr3w1inqd8HKAEvEYwEfRXkHrZZ3yjjshnNf4wpVk7EhlV+ahomC1bZmrwI0BJ9L9JWNkckaYuO7zxERlCno+liZGbPW0b19ErJ6xe/Smk7M3jWk63h7FooFGWsdIxcVm4yZjL3XK0RqUmfRWehmygH9qR4tPqExakWm+OFN8tchQY32GtTFcgb9Xhw99jpkMVehRSKqz3TZQFSFtuLg28hfrxq7ohm7nzEUE=
