language: node_js
branches:
  only:
  - master
addons:
  ssh_known_hosts: 178.79.159.178
script: ./node_modules/.bin/gulp dist
before_deploy:
  - openssl aes-256-cbc -K $encrypted_b29e5146ef90_key -iv $encrypted_b29e5146ef90_iv -in .travis/deploy-key.enc -out /tmp/deploy-key -d
  - rm .travis/deploy-key.enc
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy-key
  - ssh-add /tmp/deploy-key
  - rm -f /tmp/deploy-key
deploy:
  skip_cleanup: true
  provider: script
  # https://linux.die.net/man/1/rsync
  script: rsync -qazr --no-perms --force --delete $TRAVIS_BUILD_DIR/public/* deploy@178.79.159.178:/var/www/hugoduraes.com/public/
  on:
    branch: master
notifications:
  email: false
  slack:
    secure: FW8FoHhlhFPlRyiQ5Izs6mzqcmE1Dp3XPOjyfdZftPFX4C0uTRbTKl5/3f44TMAACBTTRAvpkRIkTJk1H4UmWDRo1G4ZpwHflxKaN7jiPRxn+n6Cp8mKjvyGgV2mdmEXMH99CnELrqicMHoyXKnPbEuAaWXbbz69qKFfWTPgFS6TFcXwzGO9o55zbzpd5jz9qu91TvAn807D3w/yz/uot5UYubYSZpZiwHS9C9hGL0iNbwni3CuYFTW6EHHmvDUyQrtxUsktkXJPetlD2n7T+1UESQZYL6AX73lQf5oY7623h3u2GskKSNJxmp5KrqY4CQP+CppjpHQAFq8815CgIACta8nZBKzJH8n66k4zUhXslE5A1fbgTj9mOe+SiUa7WtARC7HjhrTgbCY6M+bydbLwF563HEETFVUoVYW/C/4wTopB8MdeVMkT3wlAusZD25clPBbpEI31Afc9LOUnPFkoQ3RoNAR0UvwWZ45Jcu27xb0Wqscajn0V8bUyrK/ukTZZBMhZxfgo0aimIJkduacB4z5oGfWXEt4SbahiRwBcrjmfbTNzYRopltkEGz289coRlGQdvApwS4xekiigu85F+0p4k3Vr+lNjtvcQuGypPXkKTVZs6CNa+uLRqZefLXQk8cd23YtiHIrQU1K3n+BShWQ8dxf+SPWncIkFetI=
